#pragma config(Sensor, S2, soundSensor, sensorSoundDB)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int speed = 50;

void go(char* direction, int time) {
	// 690 is a good turn time :D
	if (direction == "forward") {
		motor[motorB] = speed;
		motor[motorC] = speed;
		wait1Msec(time);
	}
	if (direction == "backward") {
		motor[motorB] = speed*-1;
		motor[motorC] = speed*-1;
		wait1Msec(time);
	}
	if (direction == "left") {
		motor[motorB] = 50;
		motor[motorC] = 0;
		wait1Msec(time);
	}
	if (direction == "right") {
		motor[motorB] = 0;
		motor[motorC] = 50;
		wait1Msec(time);
	}
	if (direction == "stop") {
		motor[motorB] = 0;
		motor[motorC] = 0;
		wait1Msec(time);
	}
}

task main( ){
	// Your code goes here
}
